### ISSUE TITLE
Drop ubuntu-18.04 from the CI matrix

### ISSUE THREAD

**Issue by rollbear** [rollbear/trompeloeil#281]
Github actions is removing support for the ubuntu-18.04 image later this year. Unfortunately stepping up to 20.04 is not as straight forward as one would like. The older clang compilers are not readily available, and some gcc:s fail too.

**Comment by offa** [comment]
You can use containers which makes the build independed from host image:

```yml
[…]
    container:
      image: ${{ matrix.build_config.compiler == 'clang' && 'teeks99/clang-ubuntu' || matrix.build_config.compiler }}:${{ matrix.build_config.version }}
[…]
```
